imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: @PumukitNewAdminBundle/Resources/config/config.yml }
    - { resource: encoder.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        pumukit2_info: "%pumukit2.info%"
        locales:       "%pumukit2.locales%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# MongoDB configuration
doctrine_mongodb:
    connections:
        default:
            server: "%mongodb_server%"
            options: {}
    default_database: "%mongodb_database%"
    document_managers:
        default:
            auto_mapping: true
            filters:
                frontend:
                    class:     Pumukit\SchemaBundle\Filter\SchemaFilter
                    enabled:   false
                channel:
                    class:     Pumukit\SchemaBundle\Filter\ChannelFilter
                    enabled:   false


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOSUser Configuration
fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: Pumukit\SchemaBundle\Document\User

# Pumukit2 parameters
parameters:
    pumukit2.info:
        title:        "UCies.tv"
        description:  "Cíes University TV Website"
        keywords:     "webtv, Tv, Cies University, uvigo, uvigotv, pumukit"
        email:        "tv@ucies.tv"
        logo:         "/bundles/pumukitwebtv/images/UCies/logo.png"
    pumukit2.locales:
        - es
        - en
    pumukit2.uploads_dir: "%kernel.root_dir%/../web/uploads"
    pumukit2.uploads_url: "/uploads"
    pumukit2.inbox:   "%kernel.root_dir%/../web/storage/inbox"
    pumukit2.tmp:     "%kernel.root_dir%/../web/storage/tmp"
    pumukit2.delete_on_disk: true

pumukit_opencast:
    host: "%opencast_host%"
    username: "%opencast_username%"
    password: "%opencast_password%"
    player: "%opencast_player%"
