pumukit_encoder:
    thumbnail:
        width: 304
        height: 242
    cpus: 
        local:
            host: 127.0.0.1
    profiles:
        master_copy:
            display: false
            wizard: true
            master: true
            resolution_hor: 0
            resolution_ver: 0
            framerate: 0
            channels: 1
            audio: false
            bat: 'cp "{{input}}" "{{output}}"'
            streamserver:
                name: Localmaster
                type: store
                host: 127.0.0.1
                description: Local master server
                dir_out: "%kernel.root_dir%/../web/storage/masters"
            app: cp
            rel_duration_size: 1
            rel_duration_trans: 1
        master_video_h264:
            display: false
            wizard: true
            master: true
            format: mp4
            codec: h264
            mime_type: 'video/x-mp4'
            extension: mp4
            resolution_hor: 0
            resolution_ver: 0
            bitrate: 1 Mbps
            framerate: 25
            channels: 1
            audio: false
            bat: |
                ffmpeg -y -i "{{input}}" -acodec libfdk_aac -vcodec libx264 -preset slow -crf 15 -threads 0 "{{output}}"
            streamserver:
                name: Localmaster
                type: store
                host: 127.0.0.1
                description: Local master server
                dir_out: "%kernel.root_dir%/../web/storage/masters"
            app: ffmpeg
            rel_duration_size: 1
            rel_duration_trans: 1
        video_h264:
            display: true
            wizard: true
            master: false
            tags: html5
            format: mp4
            codec: h264
            mime_type: 'video/x-mp4'
            extension: mp4
            resolution_hor: 0
            resolution_ver: 0
            bitrate: 1 Mbps
            framerate: 25
            channels: 1
            audio: false
            bat: |
                ffmpeg -y -i "{{input}}" -acodec libfdk_aac -vcodec libx264 -preset slow -crf 15 -threads 0 "{{output}}"
            streamserver:
                name: Localhost
                type: download
                host: 127.0.0.1
                description: Local download server
                dir_out: "%kernel.root_dir%/../web/storage/downloads"
                url_out: "/storage/downloads"
            app: ffmpeg
            rel_duration_size: 1
            rel_duration_trans: 1
        audio_aac:
            display: true
            wizard: true
            master: false
            tags: html5 audio
            format: mp4
            codec: aac
            mime_type: 'audio/x-mp4'
            extension: m4a
            resolution_hor: 0
            resolution_ver: 0
            bitrate: 1 Mbps
            framerate: 0
            channels: 1
            audio: true
            bat: |
                ffmpeg -y -i "{{input}}" -acodec libfdk_aac -vn -threads 0 "{{output}}"
            streamserver:
                name: Localhost
                type: download
                host: 127.0.0.1
                description: Local download server
                dir_out: "%kernel.root_dir%/../web/storage/downloads"
                url_out: "/storage/downloads"
            app: ffmpeg
            rel_duration_size: 1
            rel_duration_trans: 1
        sbs:
            display: true
            wizard: false
            master: false
            tags: html5
            format: mp4
            codec: aac
            mime_type: 'video/x-mp4'
            extension: mp4
            resolution_hor: 0
            resolution_ver: 0
            bitrate: 1 Mbps
            framerate: 0
            channels: 1
            audio: false
            bat: |
                ffmpeg -i {{presenter/delivery}}  -i {{presentation/delivery}} -filter_complex "[0:v]scale=640:-1[a],[a]pad=1280:720:0:120+((480-in_h)/2) [bg],[1:v]scale=640:-1[b],[bg][b]overlay=w:120+((480-h)/2)" -r 25 -vcodec libx264 -preset medium -crf 22 -maxrate 1100k -bufsize 1835k -acodec libfdk_aac -ac 2 -ar 44100 -b:a 128k -f mp4 -y "{{output}}"
            streamserver:
                name: Localhost
                type: download
                host: 127.0.0.1
                description: Local download server
                dir_out: "%kernel.root_dir%/../web/storage/downloads"
                url_out: "/storage/downloads"
            app: ffmpeg
            rel_duration_size: 1
            rel_duration_trans: 1

