pumukitnewadmin_seriestype_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.seriestype:indexAction
        _sylius:
            filterable: true

pumukitnewadmin_seriestype_create:
    pattern: /create
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.seriestype:createAction
        _sylius:
            redirect: pumukitnewadmin_seriestype_index

pumukitnewadmin_seriestype_update:
    pattern: /{id}/update
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.seriestype:updateAction
        _sylius:
            redirect: pumukitnewadmin_seriestype_index

pumukitnewadmin_seriestype_batch_delete:
    pattern: /batchdelete
    methods: [DELETE]
    defaults:
        _controller: pumukitnewadmin.controller.seriestype:batchDeleteAction
        _sylius:
            redirect: pumukitnewadmin_seriestype_index

pumukitnewadmin_seriestype_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: pumukitnewadmin.controller.seriestype:deleteAction
        _sylius:
            redirect: pumukitnewadmin_seriestype_index

pumukitnewadmin_seriestype_copy:
    pattern: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.seriestype:copyAction
        _sylius:
            redirect: pumukitnewadmin_seriestype_index

pumukitnewadmin_seriestype_show:
    pattern: /{id}/show
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.seriestype:showAction

pumukitnewadmin_seriestype_list:
    pattern: /list
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.seriestype:listAction
        _sylius:
            filterable: true
